/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_citrine_ecos_NativeECOS */

#ifndef _Included_io_citrine_ecos_NativeECOS
#define _Included_io_citrine_ecos_NativeECOS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      io_citrine_ecos_NativeECOS
 * Method:     EcosSolve
 * Signature:  (IIIII[I[D[I[I[D[I[I[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_io_citrine_ecos_NativeECOS_EcosSolve
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:      io_citrine_ecos_NativeECOS
 * Method:     EcosVer
 * Signature:  ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_citrine_ecos_NativeECOS_EcosVer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
